openapi: 3.0.0
paths:
  /products:
    get:
      summary: Get all products
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
      tags:
        - Products

  /products/{id}:
    get:
      summary: Get simple product
      description: Get product by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not exist
      tags:
        - Product

    put:
      summary: Create / modify product
      description: Create / modify product by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        "201":
          description: "Created"

        "404":
          description: Product not exist
        "403":
          description: Wrong password
        "401":
          description: Unathorized

      security:
        - basicAuth: []
    delete:
      summary: Delete product
      description: Delete product by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
            format: uuid

      responses:
        "200":
          description: "Success"

        "404":
          description: Product not exist
        "403":
          description: Wrong password
        "401":
          description: Unathorized

      security:
        - basicAuth: []
info:
  title: Product Service
  description: Example product Service
  version: 1.0.0
  contact: {}
tags: []
servers:
  - url: https://uj2cycpqbe.execute-api.eu-north-1.amazonaws.com/dev
    variables: {}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: ProductTitle
        description:
          type: string
          example: Short Product Description
        price:
          type: number
          example: 25
        count:
          type: number
          example: 3
      required:
        - title
        - price
        - count
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
