openapi: 3.0.0
paths:
  /products:
    get:
      summary: Get all products
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
      tags:
        - Products

  /products/{id}:
    get:
      summary: Get simple product
      description: Get product by id
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not exist
      tags:
        - Products

info:
  title: Product Service
  description: Example product Service
  version: 1.0.0
  contact: {}
tags: []
servers:
  - url: https://dv723ezvf7.execute-api.eu-north-1.amazonaws.com/dev
    variables: {}
components:
  schemas:
    Product:
      type: object
      properties:
        description:
          type: string
          example: Short Product Description
        title:
          type: string
          example: ProductTitle

        id:
          type: string
          format: uuid
        price:
          type: number
          example: 25
      required:
        - title
        - price
        - id
